apiVersion: v1
kind: Service
metadata:
  name: sample-docker-app-service
  labels:
    app: sample-docker-app
spec:
  ports:
  - nodePort: 32008
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: sample-docker-app
  sessionAffinity: None
  type: NodePort